# -*- coding: utf-8 -*-
"""Assignment-3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RQkVNbNhxMJXnKFPLfVkFmuoxYyMr1v5

###Program 1
"""

class Employee:

    #Creation of a data member to count the number of Employees
    number_of_employee = 0

    #Creation of a constructor to initialize name, family, salary, department
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department

        Employee.number_of_employee += 1

#Creation of a function to average salary
def calculate_average_salary(employees):
    total_salary = sum(Employee.salary for Employee in employees)
    average_salary = total_salary / len(employees)
    return average_salary

#Creation of a Fulltime Employee class and it should inherit the properties of Employee class
class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)

#Creation of instances of Employee class
employees_list = [Employee("Vardhan", "Vardhan Family", 85630, "HR Department"),
                  Employee("Yash", "Yash Family", 65380, "Finance Department"),
                  Employee("Harsha", "Harsha Family", 59840, "Information security Department")]

#Creation of instances of Fulltime Employee class
fulltime_employee = FulltimeEmployee("Tejesh", "Tejesh Family", 70000, "Admin Department")

#Calling their member functions.
average_salary_result = calculate_average_salary(employees_list)

print(f"Average Salary: ${average_salary_result}")

print(f"Total Employees: {Employee.number_of_employee}")

print(f"Fulltime Employee Department: {fulltime_employee.department}")

"""### Program 2"""

import numpy as num

random_vector = num.random.uniform(1, 20, 20)

Array = random_vector.reshape((4, 5))

max_values = num.max(Array, axis=1)

Array[Array == max_values[:, num.newaxis]] = 0

print(Array)